name: CI Pipeline

on: [workflow_dispatch, push]


jobs:
  init:
    runs-on: ubuntu-latest
    
    outputs: 
      ACR_NAME: ${{ steps.define-variables.outputs.ACR_NAME }}
      NOME: ${{ steps.test.outputs.NOME }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Test
        id: test
        uses: ./.github/actions/test

      - name: Define Variables
        id: define-variables
        uses: ./.github/actions/define-variables
        with:
          ACR: ${{ vars.ACR }}
      
      - name: ACR OUTPUTS
        run: |
          echo "NOME: ${{ steps.test.outputs.NOME }}"
          echo "ACR_NAME: ${{ steps.define-variables.outputs.ACR_NAME }}"

  step-2:
    needs: [init]
    runs-on: ubuntu-latest
    steps:
      - name: ACR output
        run: |
          echo "ACR_NAME: ${{ needs.init.outputs.ACR_NAME }}"